//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShadowsocksR.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShadowsocksR.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 1.0.1.0 1.0.1.255
        ///1.0.2.0 1.0.3.255
        ///1.0.8.0 1.0.15.255
        ///1.0.32.0 1.0.63.255
        ///1.1.0.0 1.1.0.255
        ///1.1.2.0 1.1.3.255
        ///1.1.4.0 1.1.7.255
        ///1.1.8.0 1.1.8.255
        ///1.1.9.0 1.1.9.255
        ///1.1.10.0 1.1.11.255
        ///1.1.12.0 1.1.15.255
        ///1.1.16.0 1.1.31.255
        ///1.1.32.0 1.1.63.255
        ///1.2.0.0 1.2.1.255
        ///1.2.2.0 1.2.2.255
        ///1.2.4.0 1.2.4.255
        ///1.2.5.0 1.2.5.255
        ///1.2.6.0 1.2.7.255
        ///1.2.8.0 1.2.8.255
        ///1.2.9.0 1.2.9.255
        ///1.2.10.0 1.2.11.255
        ///1.2.12.0 1.2.15.255
        ///1.2.16.0 1.2.31.255
        ///1.2.32.0 1.2.63.255
        ///1.2.64.0 1.2.127.255
        ///1.3.0.0 1.3.255 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string chn_ip {
            get {
                return ResourceManager.GetString("chn_ip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 # translation for Simplified Chinese
        ///
        ///# Menu items
        ///Mode=代理模式
        ///Disable system proxy=禁用代理
        ///Enable system proxy=启用代理
        ///Proxy rule=代理规则
        ///Bypass LAN=绕过局域网
        ///Bypass LAN and China=绕过局域网和大陆
        ///Bypass LAN and not China=绕过局域网和非大陆
        ///User custom=用户自定义
        ///Disable bypass=全局代理
        ///Edit Host file=编辑用户自定义规则
        ///Edit China IP file=编辑大陆规则
        ///(empty group)=(未分组)
        ///Servers=服务器
        ///Edit servers=编辑服务器
        ///Import servers from file=从文件导入服务器
        ///Config File=配置文件
        ///Servers Subscribe=服务器订阅
        ///Subscribe setting=服务器订阅设置
        ///Update subscribe SSR node=更新服务器订阅
        ///Updat [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string cn {
            get {
                return ResourceManager.GetString("cn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] libsscrypto_dll {
            get {
                object obj = ResourceManager.GetObject("libsscrypto_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] libsscrypto64_dll {
            get {
                object obj = ResourceManager.GetObject("libsscrypto64_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] mgwz_dll {
            get {
                object obj = ResourceManager.GetObject("mgwz_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ngnl {
            get {
                object obj = ResourceManager.GetObject("ngnl", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 listen-address __PRIVOXY_BIND_IP__:__PRIVOXY_BIND_PORT__
        ///show-on-task-bar 0
        ///activity-animation 0
        ///forward-socks5 / 127.0.0.1:__SOCKS_PORT__ .
        ///hide-console
        ///__BYPASS_ACTION__
        /// 的本地化字符串。
        /// </summary>
        internal static string privoxy_conf {
            get {
                return ResourceManager.GetString("privoxy_conf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] privoxy_exe {
            get {
                object obj = ResourceManager.GetObject("privoxy_exe", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ss16 {
            get {
                object obj = ResourceManager.GetObject("ss16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ss20 {
            get {
                object obj = ResourceManager.GetObject("ss20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ss24 {
            get {
                object obj = ResourceManager.GetObject("ss24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ssw128 {
            get {
                object obj = ResourceManager.GetObject("ssw128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 # translation for Traditional Chinese
        ///
        ///# Menu items
        ///Mode=代理模式
        ///Disable system proxy=禁用代理
        ///Enable system proxy=啟用代理
        ///Proxy rule=代理規則
        ///Bypass LAN=繞過區域網路
        ///Bypass LAN and China=繞過區域網路和大陸
        ///Bypass LAN and not China=繞過區域網路和非大陸
        ///User custom=用戶自定義
        ///Disable bypass=全局代理
        ///Edit Host file=編輯用戶自定義規則
        ///Edit China IP file=編輯大陸規則
        ///(empty group)=(未分組)
        ///Servers=伺服器
        ///Edit servers=編輯伺服器
        ///Import servers from file=從文件導入伺服器
        ///Config File=設定檔
        ///Servers Subscribe=伺服器訂閱
        ///Subscribe setting=伺服器訂閱設置
        ///Update subscribe SSR node=更新伺服器訂閱
        ///Up [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string zh_tw {
            get {
                return ResourceManager.GetString("zh_tw", resourceCulture);
            }
        }
    }
}
